apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: basic-auth


# kubectl -n milvus --kubeconfig ~/iot/kubeconfigs/legion.yaml create secret generic basic-auth --from-file=auth