#ENC[AES256_GCM,data:HQ2ozOdUUvRrwgOWmhE/n7fC1UhVTOOqklmq,iv:OY9HPz3lZE7DwolzfO0BNqd7CDFw4D/EXJibCpvHTFk=,tag:BgjDG6OnbFUDRITi4vKq9Q==,type:comment]
#ENC[AES256_GCM,data:1wvLremRI1g5gwKjLuC1zjByD3nm9mV3ltWSrpBLSA==,iv:v636HPxy1+7GPQyHDiZJmTik34mP0HdJZUSsj7FP/+Q=,tag:KR8YrIZfwO7BVDFDz9dbiA==,type:comment]
#ENC[AES256_GCM,data:+x1HszTX48YF0dVL0D+LJgUkrZZVmILjtV3RzQHp9UdzoH9QxlmseTfEvYkC6bu+OrR+,iv:PzX122jWqS7oDOLBUs7HdgcVyCvhQiXiManQBb6zvBI=,tag:v4aaPxCx4RatRHGBA388TA==,type:comment]
image:
    registry: ENC[AES256_GCM,data:aYQGoyQR3qdc9BMSba6HP7MD3OIy,iv:QeYUT8bvxalqvcdvBbShpFqHDI8LNHHpk2FVC3g0878=,tag:glDnFZ0tQeLpQeoI/csXdA==,type:str]
    path: ENC[AES256_GCM,data:4/ECLI6Kly4=,iv:z6cChPZ1jXkpzMurYoYp+wLvdwBgwjEQKDphN2b9Bng=,tag:7EZNu2uNUUH0fnw+QhY6UQ==,type:str]
appConfig:
    collector:
        camera_fqdn: ENC[AES256_GCM,data:vJjzEQQxwWrv,iv:y3BmHg+8MCI4LGptC0wDOTQMxo06frdfQ6Fh2db4+kM=,tag:AZI3g9AM2ZDNP/98YAmbOA==,type:str]
        camera_friendly_name: ENC[AES256_GCM,data:2zLK9w==,iv:8WlG8s+tXMzJRAo/6dOjWBgjrGQFB3UIy5686wsO22U=,tag:Af8+anXAoyP38X8sdK0C2g==,type:str]
        camera_username: ENC[AES256_GCM,data:oL6Zbg==,iv:2X3Ucep7kqDgEI5XNCv3GcTkrB0ZFdroXnq9+M5QKIE=,tag:aZ4d6ceJWhuc9bMajpJ1Ig==,type:str]
        camera_password: ENC[AES256_GCM,data:ukWkgzaAO/4=,iv:CiCasa40u79P+pv/w1p4sbm2wBjUEXiv22yvcJnkBKo=,tag:acZvf/pnGMaBZ/HP1p1j2w==,type:str]
    kafka:
        broker_url:
            - ENC[AES256_GCM,data:syvkd9D35azcXtw4mBBM7MpykkW2,iv:K+c88xO17QqBma6PRPQWdT1amfXU1STe4hixfYN6/3w=,tag:EX2goHTXlHSvsQxOpCb8Gg==,type:str]
        security_protocol: ENC[AES256_GCM,data:2i/b2Y8uRig=,iv:XUnjRw/U1sHU/c/SaiysmbndRkWtPwSx5Q1mii/ILGs=,tag:u4X1b8f90PMWPJ/0bd5Hxg==,type:str]
        sasl_mechanism: ENC[AES256_GCM,data:Ws5B8286KrMJTqSokg==,iv:VkM7x09JzB/Vlq9d/nI8lkfBeyFkovDQGdRp3xXTyRE=,tag:8rrEJaFKtrVIFK3k2LrCvw==,type:str]
        sasl_plain_username: ENC[AES256_GCM,data:Izt5l+aoUpXGnl1hX0RQyKw=,iv:giakqloSOCtg59/WjoiKwxDM5yLA/zBbTqRgzVezOak=,tag:hSjNHvKCNVPWA7OTSwQq2g==,type:str]
        sasl_plain_password: ENC[AES256_GCM,data:xHe93wn5ksHPIV92R6nQD5uvTXZr3hzFcTopz61jXrk=,iv:JMeypWOcqN4JE9CVnZ7EtKBgL+tW5a20vmbobx23zVM=,tag:KkoCGZht4DyNuSgsiDF0BA==,type:str]
        subscribe_topic_prefix: ENC[AES256_GCM,data:d7my5FfXigIKXcZhqg==,iv:1Fn3uWwXUvg4TJR+0l2KXl92q7/KYGb08ErVe687ozQ=,tag:diTkvTC40BJiyZMwC8/bGw==,type:str]
        produce_topic_prefix: ENC[AES256_GCM,data:JBsH2WfQxEHX9E3mLYc=,iv:bq2+HR1HebpRVVofTkArz5jhisIL69IzNe0+2mIXc4M=,tag:N0E+OPr7DyR29OqObJZvVg==,type:str]
        value_serialiser: ENC[AES256_GCM,data:87b4BBcW4ETj4p1mXFuzJuOSRvL3Uj2Y/CylCBVYZYyIKyO+5j0=,iv:rYtPCduUgcDgaXiBPYSEtU41bTXEDLanNOF+LQAQrdk=,tag:39y+0eP3LLaCo7dWYz67kQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14gv5gchyxmg76hnf69lsr6vqzgx8dka5kjnedrfesg2nt0yfhavs4n0xac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SE42UW5HdjNaYlJibFl0
            bUd5YnVwbTIrak16VSt6MUdFUVVFdEtWQmpFCmpkTkpmajNvTWJEc1NubTdpZ2hX
            SGtWZUtEUTRSdjhBNFZqSUN4UHNzaFkKLS0tIGVHOW9jeTVldXhPRGFOQ2s5dUoy
            QUVlbFNlSTJ4ZEdxKzc1eGlTL3U2RTQKk/dy/7bUSDiA97/tvEyTljnAZWbpTYfB
            6EiuQ/g3mznCpKKqbvwBm9O2TMTDvysehqmFHFUMvQU84whbI/gVTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qyehj2cqg9ud8eyctskq5ze8ynau06ehxe5dx6lq0jtqm5wf45dq2gjrjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZGtiSWhkcWwzQ1lEUEtT
            N01vMTkvSUNQZU4wa2l2NTJRNER3eTYrM0JNCjNTUXFHdk5DVThraWFPM2lvbXJk
            dDIvYjZ5UmRrSi9iUGNYTlpkTUcxRXMKLS0tIEZMZFQwTW54WUVsb2Uvc3ZudGMy
            b09KcmVyMTBPVnpFR29yT0t2QWJzMXMKFLjjHvFJ5eWaLIxFs/AcWAtYpwej+6yV
            bLJDEVAe0ToQZ5SEvSJuzUS7CLgA2li+zUCkYEK6CzCfy+ZCmSfmHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzynsad4vklswdacwm7jq6hptd9u9n9v3lq9l3xdhfcyke94a9lsa82xh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYVFGRlVWcXRFRUgvOGVo
            MUUvcGdyajNhZEZoK1RIY0g5eWw3WnFidG1jClVoV3gxRGV2aUNuT2FoamtGa1BV
            UXMxOVRFL25WdkdlZFNJSW1JQjhweWcKLS0tIHJ5UVdQcFY3U1BFZFFnZVpGd1Vk
            M1VsZTRqbHJLOGJsbjJUNDhpbjNSaGsK8Wy7pPdS/VdYzXNf00ByxPoSoVdGxIUw
            nBDVf+UsMEl9cIJJc9rCUSAoRhcVdMUnAbqAOdPym28SJSXMN67VCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-16T21:31:16Z"
    mac: ENC[AES256_GCM,data:uq0+wNWhz8nOV8nUUaqmPBSdm+Y5O0BYUK3HnIqERMbaGL2lW8Fmde3Kfv8D+lro0bdAhQqIgWCncO8s73OcHX0oJFUAMCkX8aU677DhQR6tgVXac99eLvcKRVWJZkEvGVlZRXGbDBS/sPQ8573ZSAH2YcaIzncHA914WrZkIHk=,iv:FEZZFHHCSXWdlYK4lumnHQ9hNSzcUkZawFJ7mRSKfng=,tag:3zbOR/OYZ7YyJHZjtaiBIg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
