---
# It would be a good idea to create a "central config" for this, so colletors can auto-config themselves
general:
  app_name: securia_yu
  default_debug_level: DEBUG
storage:
  bucket_name: test
  endpoint_hostname: 10.0.0.59
  endpoint_method: http
  port: 32650
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
metrics:
  enabled: True
api:
  uri: http://10.0.0.95:8088/securia
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: False