---
# It would be a good idea to create a "central config" for this, so colletors can auto-config themselves
general:
  app_name: securia_ui
  version: latest
  default_debug_level: DEBUG
  auto_refresh_miliseconds: 5000
  dataframe_cache_expire_seconds: 30
storage:
  bucket_name: test
  endpoint_hostname: 10.0.0.95
  endpoint_method: http
  port: 32650
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
metrics:
  enabled: True
api:
  uri: http://10.0.0.95:8088/securia
  static_content_root: http://localhost:8501/app/static
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: False