---
# It would be a good idea to create a "central config" for this, so colletors can auto-config themselves
general:
  app_name: yolo_processor
  default_debug_level: DEBUG
  version: latest
  test_mode: False
yolo:
  enabled: True
  model: yolov8l.pt
  augment: False
  time_format: "%Y%m%d_%H%M%S.%f%z"
  image_filename_prefix: "predict"
  write_local_file: False
  temp_output_folder: yolo_tmp
  save_predict_output: True
  save_predict_crops: False
storage:
  bucket_name: test
  endpoint_hostname: 10.0.0.95
  endpoint_method: http
  port: 32650
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
kafka:
  broker_url: ["10.0.0.95:32394"]
  security_protocol: SASL_PLAINTEXT
  sasl_mechanism: SCRAM-SHA-512
  sasl_plain_username: admin
  sasl_plain_password: Xr4i0hhtlnxsPZ9aMfMgM7DhZraddu3K
  subscribe_topic_prefix: preprocessor.out.image
  produce_topic_prefix: yolo.processor.out.
  dlq_topic_prefix: yolo.dlq.out.
  consumer_group: yoloprocessor
  auto_offset_reset: earliest
  enable_auto_commit: True
  value_serialiser: lambda x:json.dumps(x).encode('utf-8')
api:
  uri: http://10.0.0.95:8088/securia
  username: apiuser
  password: handed-renovate-silencer-starry
  default_port: 8089
  debug_level: info
  debug_enabled: False
scheduler:
  enabled: False
metrics:
  enabled: True
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: False