apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    repoURL: https://github.com/VertigoOne1/securia.git
    path: helm/infra
    targetRevision: HEAD
    plugin:
      name: helmfile
      env:
        - name: HELMFILE_GLOBAL_OPTIONS
          value: "--environment dev"
        - name: HELMFILE_ENV_FILE # Contains BASE_VERSION and RUN_NUMBER
          value: .env
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    manual: {}

  info:
    - name: 'Keycloak'
      value: 'https://login.marnus.com'