---
# It would be a good idea to create a "central config" for this, so colletors can auto-config themselves
general:
  app_name: securia_maintenance
  default_debug_level: DEBUG
  version: latest
maintenance:
  enabled: True
  prune_data_older_than_days: 7 # prunes all metadata and related images from object storage
  prune_images_older_than_days: 3 # prunes only images from object storage leaving the meta
  prune_data_check_interval_seconds: 13
  prune_images_check_interval_seconds: 19
api:
  uri: http://10.0.0.95:8088/securia
  username: apiuser
  password: handed-renovate-silencer-starry
  default_port: 8191
  debug_level: info
  debug_enabled: False
scheduler:
  enabled: True
metrics:
  enabled: True
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: False