---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
  generation: 1
  name: le-prod-http
spec:
  acme:
    email: marnus@gmail.com
    preferredChain: ''
    privateKeySecretRef:
      name: le-prod-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-staging-http
spec:
  acme:
    email: marnus@gmail.com
    preferredChain: ''
    privateKeySecretRef:
      name: le-staging-account-key
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: traefik