# Default values for hikcol.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

replicaCount: 1

image:
  name: "collector-hikvision"
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

postfix: "hikcol"

app:
  general:
    app_name: collector-hikvision
    app_debug_level: INFO

appConfig:
  general:
    app_name: collector-hikvision
    default_debug_level: DEBUG
    version: dev
  collector:
    enabled: True
    capture_interval: 5
    write_local_file: False
    temp_output_folder: /tmp/images
    channel_delay_time: 0.3
    collection_timeout: 10
    time_format: "%Y%m%d_%H%M%S.%f%z"
    image_filename_prefix: "image"
    channels:
      - 101
      - 201
      - 301
      - 401
      - 501
      - 601
      - 701
      - 801
  api:
    default_port: 8299
    debug_level: debug
    debug_enabled: False
  scheduler:
    enabled: True
  metrics:
    enabled: True
  logging:
    enable_file_log_handler: False
    enable_stdout_log_handler: True
    enable_kafka_log_handler: False

service:
  type: ClusterIP
  port: 8088
  name: hikcol

serviceAccount:
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "hikcol-sa"
  bindingPostfix: "-crb"

persistence:
  # -- use a PVC to persist data
  enabled: False
  # -- the desired access modes the volume should have.
  accessModes:
    - ReadWriteOnce
  # -- Annotations to be added to the PersistentVolumeClaim
  annotations: {}
  # -- provide an existing PersistentVolumeClaim
  existingClaim: ""
  # -- Name of the StorageClass required by the claim.
  storageClassName: "local-path"
  # -- represents the minimum and maximum resources the volume should have.
  resources:
    requests:
      storage: 16Gi

ingress:
  # -- Enable ingress record generation
  enabled: false
  # -- IngressClass that will be be used to implement the Ingress
  className: ""
  # -- Additional annotations for the Ingress resource
  annotations: {}
    # cert-manager.io/cluster-issuer: cluster-issuer-name
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- An array with hosts and paths
  # @default -- see [values.yaml](./values.yaml)
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- An array with the tls configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 48Mi

nodeSelector: {}

tolerations: []

affinity: {}
