yamlApplicationConfig:
    kafka:
        clusters:
            - name: ENC[AES256_GCM,data:NfOhLeemnGJohWSOliKj,iv:Th3dYOV6QOAGTchoHgMvZQRXtq8dJ08kWcl/PAeFRtE=,tag:Krqpxbn2J3m0s6Z4qU75yw==,type:str]
              bootstrapServers: ENC[AES256_GCM,data:o14bJmKKS/dkOpOqBK46uTy1jy8S,iv:RR+7aN1QAwFWp5aZjOrEQi1qb1tuseaARvYIEBBapP0=,tag:Lcn5c65EFLDh12H4NLIngw==,type:str]
              properties:
                security.protocol: ENC[AES256_GCM,data:W7niJ3CXdo0=,iv:M8Sxra88J3lCuYsgfYBJw74/fgcH9VMrU60DhbbYYtY=,tag:XoAu2H50ualrcorm9Rasjg==,type:str]
                sasl.mechanism: ENC[AES256_GCM,data:QKtAJ6rkV/4cip7oqQ==,iv:KAksDAXqJpIGxFYEm2zgh02iviYlg0jLLhIBCV+qnp0=,tag:XTo7EHkNO4o6O35gVwWCOA==,type:str]
                sasl.jaas.config: ENC[AES256_GCM,data:yX9mjspACAIOq0ONtaizXepDNCay/pAnnMuUFuMyVWdDiTHkKrnVZHoOdmiZxPB4Wnhe3igpPdd2lUz0mXkTYEjvkA4nVuneVZ0pCllrVDq5OaJZ6sYeniI1R3NTUc/DJQ5ly+8nEt0TknzJlXD1MnSX9HWU3aX9RRKfveh5aeG6,iv:ZdZxAxy0yMv13zhVWsAmnhLKFon/cZ1YEQPPov19iy4=,tag:D2ACz7j6sMNsrfSgTBYVAQ==,type:str]
    auth:
        type: ENC[AES256_GCM,data:aZTizCAJTFAgyw==,iv:KTMJOlf2CWeJL9udlrEcaYbToxeCtBxPpXNrsjtnb3g=,tag:zSF4eO0RV91Vy8m+2iRE/g==,type:str]
    spring:
        security:
            user:
                name: ENC[AES256_GCM,data:Fy3Lok0=,iv:Sm9Ks17lA9se4SW3Lzjllo5SgKazS3Wd4+ldCjbfJKA=,tag:1+OkNHoXqjyHiSq8FC+6Qg==,type:str]
                password: ENC[AES256_GCM,data:QeU9pwpR7GEGKqfIj+qBSs7v1KE=,iv:Un1foRK4+Nv2E6TtoI3L8kESUAaDAy4272v6KT4vQnk=,tag:pzH/cvigPcKzKsdxR/sSbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14gv5gchyxmg76hnf69lsr6vqzgx8dka5kjnedrfesg2nt0yfhavs4n0xac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONDlWTnJLSjVmNGRObVBJ
            eUtHTXBja1NPUFFDUUdDSU9PQXBoSHdjRVJBCjU0U0lOQXdEQ0NqbFRTRnhtY2FP
            cWFWTFpUdVNMUzdkMGswVHJqODMvcVkKLS0tIE94SnNZWVB6REg1cTJLKzdxbGk0
            d1RZb2RCbnB5Z0N1aEJvVi8wUitSYWMKNJGYhlCpF7friApDLSiBiqwWWo8ZPDMz
            0xeYMF6W2NRF7yuG6enltOeGAyBowJ8TIkvE91sNhHioUqyudOIrpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qyehj2cqg9ud8eyctskq5ze8ynau06ehxe5dx6lq0jtqm5wf45dq2gjrjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RkhUTGxGVzh2Y3p0UElS
            SnB0a2FUbnhwWEh0b0xGYjRDVG03cXhDUGprCjlFNXFqS0tHWk9TZFFtMXB6RkNE
            TnpJczVDUkdPcGtCb3JYNUVEdFJCTDQKLS0tIFdTNlU1aHhJZ3VWaUhySlhHOEU3
            U2RRNC9odlBmVkFCVyt2ZW9qQUNBbDQKAeVhlNjBRmWjwCrLwkwUfuRITgQv7OL/
            uXR5yySnhNBo6/ByiogJf9FccyA+pj621e5PEDFJKaB3cD/ALj3Fwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzynsad4vklswdacwm7jq6hptd9u9n9v3lq9l3xdhfcyke94a9lsa82xh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSHl0dlFFRnoxZjk5SFE0
            S2JUTVRXSkhQMGNPWUNKWUtSbHoxUkdQUUdzCkdiVFhYa0lrak5RM210K2xqeERx
            OXlhZEwrdHR0dFh0b3J4c09YQ2loazQKLS0tIGpWK1pNNVMwYkdsN3ZiMnBQY0RW
            K2pLN2JJcEtXWSttcFJCTmF4UlRJR28K4L5TWHubtze8uqIDPXu3KmUMHmXgxOGx
            mpCvFGQZgCibvT7s5zX/MIFNGCNvKKMpTSN01MgScJX5tiiHinubzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T12:14:36Z"
    mac: ENC[AES256_GCM,data:W6ubRrSQw9WT6NcVGHH3NFbB7oveKW1Tv6MKJQdCiuzSNFFmUhtIJX0Uh+N6+G0UHFmF2lU+nqm1JhFtBOOPcM4qdLpgjhTTzP9Wd1agpx83UcNwB4hqZT7bKb5rmMfW7enBkngLtW+igHQNPW5WcZTy7723bd0dCuoiW7eOgDY=,iv:/Oz5ZRHpSgAU/3gi1uQzE0VK7KdzXN/CQV1g3P0AbrI=,tag:s7mgRKyC7HVA0su/+9br5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
