apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: securia-kafka
spec:
  type: allow
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operations:
          - All
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafka-ui
  labels:
    strimzi.io/cluster: securia-kafka
spec:
  type: allow
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operations:
          - All