---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: securia-kafka-nodepool
  labels:
    strimzi.io/cluster: securia-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 64Gi
        deleteClaim: false
        class: nfs-client-ssd
  # resources:
  #   requests:
  #     memory: 16Gi
  #     cpu: 1000m
  #   limits:
  #     memory: 16Gi
  #     cpu: 2000m
  # jvmOptions:
  #   -Xms: 4096m
  #   -Xmx: 4096m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: securia-kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        tls: true
        port: 9094
        type: cluster-ip
        authentication:
          type: scram-sha-512
        configuration:
          brokers:
            - broker: 0
              advertisedHost: kafka.marnus.com
              advertisedPort: 9094
            # - broker: 1
            #   advertisedHost: kafka.marnus.com
            #   advertisedPort: 9096
            # - broker: 2
            #   advertisedHost: kafka.marnus.com
            #   advertisedPort: 9097
          brokerCertChainAndKey:
            secretName: kafka-cert
            certificate: tls.crt
            key: tls.key
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
        log4j.logger.kafka: "INFO"
        log4j.logger.org.apache.kafka: "INFO"
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 1Gi
        cpu: "1"
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 32Gi
        deleteClaim: false
    authorization:
      type: simple
      superUsers:
        - admin
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 32Gi
      deleteClaim: false
    resources:
      requests:
        memory: 512Mi
        cpu: "1"
      limits:
        memory: 512Mi
        cpu: "1"
  entityOperator:
    topicOperator: {}
    userOperator: {}
---