apiVersion: ENC[AES256_GCM,data:4RA=,iv:+kJzUip9s7xumWYHX9AsvIH/O3CuGyqil3zcef+HUe4=,tag:yugGb5mAWKUw/wJ7QHOoxg==,type:str]
kind: ENC[AES256_GCM,data:dmJTO6+G,iv:z3QQ+RHcAtqfONfY3CvGVWVhrh/tJyJ2JJDD6AEwXvg=,tag:2acZGcalBKIjAmtdjlyQHg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HThaCCv9PVwTILg=,iv:AC0tGYYkx54dZHentno15eukWGqr3iXIzyE0jeSfV30=,tag:SxAkha8n3bIcEhQxBw4/ag==,type:str]
type: ENC[AES256_GCM,data:G9ebIENm,iv:x8d1PLkOkj+1ILn9XpDFbOyRS3q7Ju7RpUj6hgtPkDY=,tag:M8P8CNtYa0KyrCmVUOG+mQ==,type:str]
data:
    CF_API_KEY: ENC[AES256_GCM,data:fllcf5lmTWL6g+c5I0COT7YHig1bkSySq4OPDHcXS3/g8bgf2bWxgKI8r+iOu3ehEqjfHA==,iv:/5lP3wN9nSTI7gO+JMBt4GTnVIZL9y7mWmL6ED1q4NM=,tag:3h/TU61n8bN/KNnF8Wdo/A==,type:str]
    CF_API_EMAIL: ENC[AES256_GCM,data:+ofHVCPHBskpfp4oWmlMhQpsQOY1GVLj,iv:uqZZHTymsJvq0vCuZucsyNiyGEobE755WoHjPf0z5qU=,tag:7a3a/OSUniEANdKwLmqDMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14gv5gchyxmg76hnf69lsr6vqzgx8dka5kjnedrfesg2nt0yfhavs4n0xac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidWxDeEx3UnNrUkMweEE3
            SDYrYUxNdm5OUG9IV2Z5UkhHUmdWcExWZkhNCnQzNlZlRWU0bVJyODh3ZFdGdGJT
            YWhMU0VpZUVmcngrcmp3UWxuMmNZaVkKLS0tIE1pcWpiRXdCeEgyNWpzc2NOdEgx
            MTdxV2hYZ0hvMUVCcVp0c0hVS3lhd3MKCadqfn4FVacLANAhqItqd8oJ47dMjU4P
            FeIqiYhdk53lbrKyA4ZMQ2zySlEaXAxGrhleOvmuQp23/TzVxHcHUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qyehj2cqg9ud8eyctskq5ze8ynau06ehxe5dx6lq0jtqm5wf45dq2gjrjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dURkMVRhYWV5dkkrRWtU
            MG5EaURBUCsxT0hsN0VHUVJCckZnU3hlMjJrCnI0dmNjMEVtVFRnOGFBVHVUL281
            eXFTOVZnYlRxazVzS2g2eEVBQnYwT2cKLS0tIDVQVTNvdHRrdjhCc2orRTBlQWpV
            R3dEVTl3UWNwdm1pVjZzSXVVTVI4dHcK1bnzXY9cWZnRURgyV8523J2YHbaP3Ch1
            M2UZUKKGpFrh+BAxmjBsCDTb3GbAs+m3ThDXwH0F3eTS7vApHZR6YQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzynsad4vklswdacwm7jq6hptd9u9n9v3lq9l3xdhfcyke94a9lsa82xh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OGoxKzlxODFqUGJRWXhX
            bHBOdVRBdXc2bXZ2SCt1amYwZ0ZSUnRwUjFBCjhYSi9ibnc5RVNLZ1ZwU3lzdnRS
            NXQ5amZsTHB1QjhqcmtQMU1tQUZCRVEKLS0tIDhqQXM0eXN4VENDYmR3c2tnS0c5
            UHZxb25zNzBFcTNPZkFielBBUG5WL2sKqkCRTxMjfLOp2zxb8XeGSq7gNsLaQHmx
            NxFbH+YxpCjkC6BbC28ZI+vZmnLYSP2GX8ZA8lduKVYYMdpIhYaheQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-07T12:30:06Z"
    mac: ENC[AES256_GCM,data:MPv94g6zFbbukamg9bxKv7yxpBbpDqHXALcgR6x19+i0qhV/cBdcbEpKRnmIxniaeFFa7dk0HikliUp2hBKTeSDUbx/s416X+8x61Gmhxe2RAfERgZ82LpPxBql2+FNIu5wuBqFUHJXemEyUPaLRJhoZTl6pjQWtBey67svw/uc=,iv:7/RdW28zgnAE/azkg2Uofa5+nwtiv8uEEUlt0FIASxI=,tag:2MG7MGFaoH/D3VpCPfOMdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
