apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.general.app_name }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: argocd
data:
  config.yml: |-
    {{- .Values.appConfig | toYaml | nindent 4 }}