apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repo.repo_name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.repo.url }}
  {{- if not (empty .Values.repo.ssh_private_key) }}
  sshPrivateKey: |
{{ .Values.repo.ssh_private_key | indent 4 }}
  {{- end }}
  {{- if not (empty .Values.repo.https_username) }}
  username: {{ .Values.repo.https_username }}
  password: {{ .Values.repo.https_password }}
  {{- end }}