---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: securia-arc-runner
spec:
  replicas: 1
  template:
    spec:
      repository: VertigoOne1/securia
      automountServiceAccountToken: true
      serviceAccountName: arc-user
      serviceAccount: arc-user
      labels:
        - "homelab"
        - "self-hosted"
      resources:
        limits:
          ephemeral-storage: 10Gi
        requests:
          ephemeral-storage: 10Gi