---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-user
  namespace: actions-runner-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-user
  namespace: securia
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: arc-user
  namespace: actions-runner-system
- kind: ServiceAccount
  name: arc-user
  namespace: securia
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: arc-user-token
  namespace: securia
  annotations:
    kubernetes.io/service-account.name: arc-user