---
# It would be a good idea to create a "central config" for this, so colletors can auto-config themselves
general:
  app_name: collector_simulator
  default_debug_level: DEBUG
  version: latest
collector:
  enabled: True
  recorder_uuid: 79981d14-7719-49b2-b6b5-f7996b73ba04
  recorder_fqdn: "244.0.0.1"
  recorder_friendly_name: "Simulator2"
  recorder_username: view
  recorder_password: "asdf1234"
  recorder_owner: "Demo2"
  recorder_type: "simulator2"
  recorder_location: "container2"
  recorder_contact: "101111"
  recorder_owner_user_id: "1"
  capture_interval: 10
  write_local_file: True
  temp_output_folder: /tmp/images
  channel_delay_time: 5
  collection_timeout: 10
  time_format: "%Y%m%d_%H%M%S.%f%z"
  image_filename_prefix: "image"
  channels:
    - 0
    - 1
    - 2
    # - 401
    # - 501
    # - 601
    # - 701
    # - 801
kafka:
  broker_url: ["10.0.0.59:32394"]
  security_protocol: SASL_PLAINTEXT
  sasl_mechanism: SCRAM-SHA-512
  sasl_plain_username: admin
  sasl_plain_password: Xr4i0hhtlnxsPZ9aMfMgM7DhZraddu3K
  subscribe_topic_prefix: collector.in.
  produce_topic_prefix: collector.out.
  value_serialiser: lambda x:json.dumps(x).encode('utf-8')
api:
  default_port: 8299
  debug_level: debug
  debug_enabled: False
scheduler:
  enabled: True
metrics:
  enabled: True
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: False