{{- if not (lookup "kafka.strimzi.io/v1beta1" "KafkaUser" .Release.Namespace collector-hikvision ) -}}
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: securia-collector
  labels:
    strimzi.io/cluster: securia-kafka
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  type: allow
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
      - resource:
          type: cluster
          name: '*'
          patternType: literal
        operations:
          - Describe
{{ end }}