---
# It would be a good idea to create a "central config" for this, so colletors can auto-config themselves
general:
  app_name: securia_api
  default_debug_level: DEBUG
storage:
  bucket_name: test
  endpoint_hostname: 10.0.0.59
  endpoint_method: http
  port: 32650
  access_key: AKIAIOSFODNN7EXAMPLE
  secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
kafka:
  broker_url: ["10.0.0.59:32394"]
  security_protocol: SASL_PLAINTEXT
  sasl_mechanism: SCRAM-SHA-512
  sasl_plain_username: admin
  sasl_plain_password: Xr4i0hhtlnxsPZ9aMfMgM7DhZraddu3K
  topic_prefix: collector.
  consumer_group: preprocessor
  auto_offset_reset: latest
  value_serialiser: lambda x:json.dumps(x).encode('utf-8')
api:
  default_port: 8088
  debug_level: debug
  time_format: "%Y%m%d_%H%M%S.%f"
  maintenance_mode: False
  secret_key: 7a61f307a3c2040fd6923cb0357a546f1bf436607f5dd5fad0ceb0c0844c6f64
  token_expiry_seconds: 86400 # 1 day
scheduler:
  enabled: False
metrics:
  enabled: True
logging:
  enable_file_log_handler: False
  enable_stdout_log_handler: True
  enable_kafka_log_handler: False
database:
  uri: 'postgresql+psycopg2://10.0.0.59:32617/securia?password=r[V>T(u:vn|9<oxgg:H<9S.|&user=securiaapi'