helmDefaults:
  cleanupOnFail: false

environments:
  dev:
    values:
      - environment: dev
      - components:
        - securia-api
        - securia-maintenance
        - securia-ui
        # - image-preprocessor
        # - collector-simulator
        # - yolo-processor
        # - collector-hikvision
      - destination_namespace: securia-dev
      - chart_version: '{{ env "BASE_VERSION" }}-{{ env "RUN_NUMBER" }}'

  prod:
    values:
      - environment: prod
      - components:
        - securia-api
        - securia-maintenance
        - securia-ui
        # - image-preprocessor
        # - collector-simulator
        # - yolo-processor
        # - collector-hikvision
      - chart_version: '{{ env "BASE_VERSION" }}-{{ env "RUN_NUMBER" }}'
---
releases:
{{ range $component := .Environment.Values.components }}
- name: {{ $component }}
  namespace: "{{ `{{ .Environment.Values.destination_namespace }}` }}"
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/charts/{{ $component }}
  version: "{{ `{{ .Environment.Values.chart_version }}` }}"
  values:
    - values/{{ `{{ .Environment.Name }}` }}/{{ $component | replace "-" "_" }}/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/{{ `{{ .Environment.Name }}` }}/{{ $component | replace "-" "_" }}/values_secrets.yaml
  set:
    - name: image.tag
      value: '{{ env "BASE_VERSION" }}-{{ env "RUN_NUMBER" }}'
    - name: appConfig.general.version
      value: '{{ env "BASE_VERSION" }}-{{ env "RUN_NUMBER" }}'
{{ end }}