helmDefaults:
  cleanupOnFail: false

environments:
  dev:
    values:
      - environment: dev
      - components:
        - securia-api
        - securia-maintenance
        # - collector-hikvision
        - securia-ui
        # - image-preprocessor
        - collector-simulator
        # - yolo-processor
      - destination_namespace: securia
      - default_version: "1.2.8"
  prod:
    values:
      - environment: prod
      - components:
        - securia-api
        - securia-maintenance
        - collector-hikvision
        - securia-ui
        - image-preprocessor
        # - collector-simulator
        # - yolo-processor
      - destination_namespace: securia-v2
      - default_version: "1.2.8"
---
releases:
  {{ range $component := .Environment.Values.components }}
- name: {{ $component }}
  namespace: "{{ `{{ .Environment.Values.destination_namespace }}` }}"
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/charts/{{ $component }}
  version: {{ env "CHART_VERSION" | default "1.2.3" }}
  values:
    - values/{{ `{{ .Environment.Name }}` }}/{{ $component | replace "-" "_" }}/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/{{ `{{ .Environment.Name }}` }}/{{ $component | replace "-" "_" }}/values_secrets.yaml
  set:
    - name: image.tag
      value: {{ env "CHART_VERSION" | default "latest" }}
    - name: appConfig.general.version
      value: {{ env "CHART_VERSION" | default "latest" }}
{{ end }}