helmDefaults:
  cleanupOnFail: false

# environments:
#   dev: {}

releases:
- name: securia-api
  namespace: {{ env "SECURIA_NAMESPACE" | default "securia" }}
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/securia-api
  version: {{ env "CHART_VERSION" | default "1.1.0" }}
  values:
    - values/dev/securia_api/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/dev/securia_api/values_secrets.yaml
- name: securia-ui
  namespace: {{ env "SECURIA_NAMESPACE" | default "securia" }}
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/securia-ui
  version: {{ env "CHART_VERSION" | default "1.1.0" }}
  values:
    - values/dev/securia_ui/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/dev/securia_ui/values_secrets.yaml
- name: image-preprocessor
  namespace: {{ env "SECURIA_NAMESPACE" | default "securia" }}
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/image-preprocessor
  version: {{ env "CHART_VERSION" | default "1.1.0" }}
  values:
    - values/dev/image_preprocessor/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/dev/image_preprocessor/values_secrets.yaml
- name: collector-hikvision
  namespace: {{ env "SECURIA_NAMESPACE" | default "securia" }}
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/collector-hikvision
  version: {{ env "CHART_VERSION" | default "1.1.0" }}
  values:
    - values/dev/collector_hikvision/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/dev/collector_hikvision/values_secrets.yaml
- name: yolo-processor
  namespace: {{ env "SECURIA_NAMESPACE" | default "securia" }}
  createNamespace: true
  chart: oci://harbor.marnus.com/securia/yolo-processor
  version: {{ env "CHART_VERSION" | default "1.1.0" }}
  values:
    - values/dev/yolo_processor/values.yaml
    - imagePullSecrets:
      - name: registrypullsecret
  secrets:
    - values/dev/yolo_processor/values_secrets.yaml