adminPassword: ENC[AES256_GCM,data:vA+KoELUZEwgRyKW5xrv3PJ4MgGQ,iv:XLzKleKd1m9+yFQ2n6cCt3PoffpAEs8BTCvVDoYwsyY=,tag:6VeO2x7GNANB2TiXQQC6Og==,type:str]
ingress:
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:2Trp+4yRUx50kYbyEBdsHA==,iv:Va6HdoOsd7gfcsvdiVPb8mhNIlhlNCBV3aaxeGbk4Bo=,tag:HYJY4E0QcjibZRG7kaqujA==,type:str]
        external-dns.alpha.kubernetes.io/target: ENC[AES256_GCM,data:rYqPdxwq1NVEdXZRh7Nc,iv:6w5RuuyIJe0vZeMs8sZJVPXQx2aJEGAgyXvPrTDezW4=,tag:bvhoY3nzQSS7092bviWXVg==,type:str]
    hosts:
        - ENC[AES256_GCM,data:PoGOuoahtoPCxNZDMNyZ0pBa,iv:lbaALDGFfr0IoSKK0epqkI38tQ4+ppsbzBfmsZYVbHk=,tag:hdlLJilSyHzPyFtDNxyxKw==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:4uAw2B9BsdmcKJ1a1xhJNyfp,iv:17cVxb4Jm1DlQMwNUYHuf2AbZlt9QFmqbfN2MFEepfg=,tag:WuqoPMmmNN4kpcL/sFKQgQ==,type:str]
          hosts:
            - ENC[AES256_GCM,data:CtbQgh+5N8gMpt03IgmC1Dis,iv:OM4aW63IW4Ir8Mn9xeOvxlPrJzntZ3kirwSj8tekVAM=,tag:Uxn32Y6ntUzAAAuqETaEOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14gv5gchyxmg76hnf69lsr6vqzgx8dka5kjnedrfesg2nt0yfhavs4n0xac
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0ZmV1BoM0k0MFVNQ3R1
            OG5pcnpRT01wOW02Q1BQVFdBR3pqK1lXdm1JCkZ4WERlWlVEN2NmMTgvVHpRaUhH
            aFRXVEE5RTlvTjRkY3hUSEI3UUp0Y2cKLS0tIHRnbjVFYmgvbVRzblVzbzNCaG45
            c3VsaEprU2t5c0N2L0FsQXRidDRSV2cK1bfEqfGJ28EcrDRocXGclozpHmfXtoz0
            K0p97fKTUuycC3kA/SoX3YewkSITM5p7NcbS09i3lhpvFNOgZVUaLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qyehj2cqg9ud8eyctskq5ze8ynau06ehxe5dx6lq0jtqm5wf45dq2gjrjg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYnRqRm1QaWs5aUdMVUxF
            YnJNNG1DVWYrWlMrS0d2RDFpUHdMd1NjNnc4CnMrQUpzYkNBNzhwU0JkTkZXaEp1
            ck9lOFlWYUZwOUhjRWR6L3JtbWRIUmMKLS0tIHpUbHc1aVpJZ3NjSGVSTGN0Uk1F
            RHlIbXFFZUVrcEppWldKM290MkdSU3MKOoLxUbI3Qoh/Z7g8XuBSN1YwHTBxQ2+C
            pGL6Bsbk8crQP6ZVQj3UeIABEtUSkSVe0iye+QHElbAaOjR8FdVpbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yzynsad4vklswdacwm7jq6hptd9u9n9v3lq9l3xdhfcyke94a9lsa82xh6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR0ZVZFc3b1lmTXY0S1NB
            eCtXdHhRRC9KV0NaNGlHRlF3UUNzRlhIMGhnCno3ZS93TE9hZDdXT3JkTk1GN2xL
            VHNnNDlwQm9HZ0FrbnVRTkJYcW1ZMWsKLS0tIFdvUS9pc0k3a0J4OVFvcXZ5Rllx
            aCsreUladUpXR213bzlnam5pRWNVRU0KZx5jSWHCOW8pl8c6haqFDJ6ItqjMm5ND
            WbkqZKtsu+XcknYLIJwBt5WduL+XQI6g8JCKhOut8CCtFKSZjtT8lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T22:24:25Z"
    mac: ENC[AES256_GCM,data:vVATmYhlMeA2ZqY/lFW1kcNhcy+aDGXzqC8BwfL4ZczdJh9dChsCO+M41Axqsm7hs/4rgobQAGvu8Lr9VuQRz5fDfUk0i9AGK0XPjzLqMVkJXK3vm2a9125t7YtdW/n+gVfvQg4eDMLN5AU4Pe89KN0Dwq9qZClpzXdenuCcQq4=,iv:CA1zV+k+/4E+8MsOWpsNQKiIPXOfYCLvqzCNm/RqdjA=,tag:y2WMNlCaaW4+lSVff6JZCw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
