version: '3.8'
services:
  collector-hikvision:
    image: ${REGISTRY_HOST}/securia/collector-hikvision:${SECURIA_TAG:-latest}
    build:
      context: ./collector_hikvision

  collector-simulator:
    image: ${REGISTRY_HOST}/securia/collector-simulator:${SECURIA_TAG:-latest}
    build:
      context: ./collector_simulator

  image-preprocessor:
    image: ${REGISTRY_HOST}/securia/image-preprocessor:${SECURIA_TAG:-latest}
    build:
      context: ./image_preprocessor

  securia-api:
    image: ${REGISTRY_HOST}/securia/securia-api:${SECURIA_TAG:-latest}
    build:
      context: ./securia_api

  securia-ui:
    image: ${REGISTRY_HOST}/securia/securia-ui:${SECURIA_TAG:-latest}
    build:
      context: ./securia_ui

  yolo-processor:
    image: ${REGISTRY_HOST}/securia/yolo-processor:${SECURIA_TAG:-latest}
    build:
      context: ./yolo_processor