services:
  collector-hikvision:
    image: ${REGISTRY_HOST}/securia/collector-hikvision:${CHART_VERSION}
    build:
      context: ./collector_hikvision
      cache_from:
       - type=registry,ref=${REGISTRY_HOST}/securia/collector-hikvision:buildcache
      cache_to:
       - type=registry,ref=${REGISTRY_HOST}/securia/collector-hikvision:buildcache,mode=max,compression=zstd,oci-mediatypes=true,image-manifest=true

  collector-simulator:
    image: ${REGISTRY_HOST}/securia/collector-simulator:${CHART_VERSION}
    build:
      context: ./collector_simulator
      cache_from:
       - type=registry,ref=${REGISTRY_HOST}/securia/collector-simulator:buildcache
      cache_to:
       - type=registry,ref=${REGISTRY_HOST}/securia/collector-simulator:buildcache,mode=max,compression=zstd,oci-mediatypes=true,image-manifest=true

  image-preprocessor:
    image: ${REGISTRY_HOST}/securia/image-preprocessor:${CHART_VERSION}
    build:
      context: ./image_preprocessor
      cache_from:
       - type=registry,ref=${REGISTRY_HOST}/securia/image-preprocessor:buildcache
      cache_to:
       - type=registry,ref=${REGISTRY_HOST}/securia/image-preprocessor:buildcache,mode=max,compression=zstd,oci-mediatypes=true,image-manifest=true

  securia-api:
    image: ${REGISTRY_HOST}/securia/securia-api:${CHART_VERSION}
    build:
      context: ./securia_api
      cache_from:
       - type=registry,ref=${REGISTRY_HOST}/securia/securia-api:buildcache
      cache_to:
       - type=registry,ref=${REGISTRY_HOST}/securia/securia-api:buildcache,mode=max,compression=zstd,oci-mediatypes=true,image-manifest=true

  securia-ui:
    image: ${REGISTRY_HOST}/securia/securia-ui:${CHART_VERSION}
    build:
      context: ./securia_ui
      cache_from:
       - type=registry,ref=${REGISTRY_HOST}/securia/securia-ui:buildcache
      cache_to:
       - type=registry,ref=${REGISTRY_HOST}/securia/securia-ui:buildcache,mode=max,compression=zstd,oci-mediatypes=true,image-manifest=true

  yolo-processor:
    image: ${REGISTRY_HOST}/securia/yolo-processor:${CHART_VERSION}
    build:
      context: ./yolo_processor
      cache_from:
       - type=registry,ref=${REGISTRY_HOST}/securia/yolo-processor:buildcache
      cache_to:
       - type=registry,ref=${REGISTRY_HOST}/securia/yolo-processor:buildcache,mode=max,compression=zstd,oci-mediatypes=true,image-manifest=true