services:
  collector-hikvision:
    image: ${REGISTRY_HOST}/securia/collector-hikvision:${SECURIA_TAG:-latest}
    build:
      context: ./collector_hikvision
      cache_from:
       - type=registry,ref=securia/collector-hikvision:buildcache
      cache_to:
       - type=registry,ref=securia/collector-hikvision:buildcache,mode=max,compression=zstd

  collector-simulator:
    image: ${REGISTRY_HOST}/securia/collector-simulator:${SECURIA_TAG:-latest}
    build:
      context: ./collector_simulator
      cache_from:
       - type=registry,ref=securia/collector-simulator:buildcache
      cache_to:
       - type=registry,ref=securia/collector-simulator:buildcache,mode=max,compression=zstd

  image-preprocessor:
    image: ${REGISTRY_HOST}/securia/image-preprocessor:${SECURIA_TAG:-latest}
    build:
      context: ./image_preprocessor
      cache_from:
       - type=registry,ref=securia/image-preprocessor:buildcache
      cache_to:
       - type=registry,ref=securia/image-preprocessor:buildcache,mode=max,compression=zstd

  securia-api:
    image: ${REGISTRY_HOST}/securia/securia-api:${SECURIA_TAG:-latest}
    build:
      context: ./securia_api
      cache_from:
       - type=registry,ref=securia/securia-api:buildcache
      cache_to:
       - type=registry,ref=securia/securia-api:buildcache,mode=max,compression=zstd

  securia-ui:
    image: ${REGISTRY_HOST}/securia/securia-ui:${SECURIA_TAG:-latest}
    build:
      context: ./securia_ui
      cache_from:
       - type=registry,ref=securia/securia-ui:buildcache
      cache_to:
       - type=registry,ref=securia/securia-ui:buildcache,mode=max,compression=zstd

  yolo-processor:
    image: ${REGISTRY_HOST}/securia/yolo-processor:${SECURIA_TAG:-latest}
    build:
      context: ./yolo_processor
      cache_from:
       - type=registry,ref=securia/yolo-processor:buildcache
      cache_to:
       - type=registry,ref=securia/yolo-processor:buildcache,mode=max,compression=zstd