name: General - Scan for secrets

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-for-secrets:

    runs-on: homelab

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified