name: Securia Push Charts

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  package-push-charts:

    environment:
      name: dev

    runs-on: homelab

    steps:
    - uses: actions/checkout@v4
    - name: Setup Helm
      uses: azure/setup-helm@v4.2.0
    - name: Package and push charts
      run: |
        export $(grep -v '^#' src/.env | xargs -d '\n')
        cd helm
        helm registry login -u '${{ vars.REGISTRY_USER }}' -p '${{ secrets.REGISTRY_SECRET }}' ${REGISTRY_HOST}
        for dir in charts/*/; do
          if [ -d "$dir" ]; then
            chart_name=$(basename "$dir")
            echo "Packaging chart: $chart_name"
            package_name=$(echo "${chart_name}" | tr '_' '-')
            helm package "$dir" --version ${SECURIA_VERSION}
            helm push $package_name-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia
          fi
        done
        rm *tgz