name: Securia - Build, Push, Deploy

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build-push-images:
    timeout-minutes: 1440

    environment:
      name: dev

    runs-on: homelab

    steps:
    - uses: actions/checkout@v4

    - name: Setup AGE
      uses: alessiodionisi/setup-age-action@v1.3.0

    - name: Check AGE version
      run: age --version

    - name: Setup SOPS
      uses: nhedger/setup-sops@v2

    - name: Check SOPS version
      run: sops --version

    - name: populate dotenvs
      run: |
        sops -i -d --input-type dotenv --output-type dotenv src/.env.secrets

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < src/.env

        cat helm/.env

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < helm/.env

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < src/.env.secrets
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_HOST }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: tests
      run: |
        ls -la
        ls -la ~/.docker
        cat ~/.docker/config.json

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config: src/buildkitd.toml
      env:
        DOCKER_CONFIG: .docker/config.json

    - name: Build and push images
      uses: docker/bake-action@v5
      with:
        source: "."
        files: "docker-compose.yaml"
        workdir: ./src
        push: true
      env:
        CHART_VERSION: ${{ env.CHART_VERSION }}-${{github.run_number}}

  package-push-charts:

    environment:
      name: dev

    runs-on: homelab

    steps:
    - uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v4.2.0

    - name: Setup AGE
      uses: alessiodionisi/setup-age-action@v1.3.0

    - name: Check AGE version
      run: age --version

    - name: Setup SOPS
      uses: nhedger/setup-sops@v2

    - name: Check SOPS version
      run: sops --version

    - name: Package and push charts
      run: |
        export $(grep -v '^#' src/.env | xargs -d '\n')
        sops -i -d --input-type dotenv --output-type dotenv src/.env.secrets
        export $(grep -v '^#' src/.env.secrets | xargs -d '\n')
        export $(grep -v '^#' helm/.env | xargs -d '\n')
        cd helm
        echo "${REGISTRY_PASSWORD}" | helm registry login -u ${REGISTRY_USERNAME} --password-stdin ${REGISTRY_HOST}
        for dir in charts/*/; do
          if [ -d "$dir" ]; then
            chart_name=$(basename "$dir")
            echo "Packaging chart: $chart_name"
            package_name=$(echo "${chart_name}" | tr '_' '-')
            helm package "$dir" --version ${CHART_VERSION}-${{github.run_number}}
            echo "Pushing chart: $chart_name"
            helm push $package_name-${CHART_VERSION}-${{github.run_number}}.tgz oci://${REGISTRY_HOST}/securia/charts
          fi
        done
        rm *tgz
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

  deploy-securia:

    environment:
      name: dev

    runs-on: homelab

    steps:
    - uses: actions/checkout@v4
    - name: Setup AGE
      uses: alessiodionisi/setup-age-action@v1.3.0

    - name: Check AGE version
      run: age --version

    - name: Setup SOPS
      uses: nhedger/setup-sops@v2

    - name: Check SOPS version
      run: sops --version

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0

    - name: populate dotenvs
      run: |
        sops -i -d --input-type dotenv --output-type dotenv src/.env.secrets

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < helm/.env

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < src/.env

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < src/.env.secrets

      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    - name: Deploy application
      uses: helmfile/helmfile-action@v1.9.1
      with:
        helmfile-args: apply
        helmfile-workdirectory: helm
        helm-plugins: >
          https://github.com/databus23/helm-diff,
          https://github.com/jkroepke/helm-secrets
        helmfile-auto-init: "true"
      env:
        CHART_VERSION: ${{ env.CHART_VERSION }}-${{github.run_number}}
        SECURIA_NAMESPACE: ${{ env.SECURIA_NAMESPACE }}
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}