name: Securia Docker Image CI

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    environment:
      name: dev

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4.2.0
      with:
        version: '<version>' # default is latest (stable)
      id: install
    - name: Build the Docker image
      run: |
        cd helm
        VERSION=1.0.0

        helm registry login -u '${{ vars.REGISTRY_USER }}' -p '${{ secrets.REGISTRY_SECRET }}' harbor.marnus.com --version ${VERSION}
        helm package charts/collector_hikvision --version ${VERSION}
        helm package charts/image_preprocessor --version ${VERSION}
        helm package charts/securia_api --version ${VERSION}
        helm package charts/securia_ui --version ${VERSION}
        helm package charts/yolo_processor --version ${VERSION}

        helm push collector-hikvision-${VERSION}.tgz oci://harbor.marnus.com:443/securia
        helm push image-preprocessor-${VERSION}.tgz oci://harbor.marnus.com:443/securia
        helm push securia-api-${VERSION}.tgz oci://harbor.marnus.com:443/securia
        helm push securia-ui-${VERSION}.tgz oci://harbor.marnus.com:443/securia
        helm push yolo-processor-${VERSION}.tgz oci://harbor.marnus.com:443/securia

        rm *tgz