name: Securia Build Images

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    environment:
      name: dev

    runs-on: homelab

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Set Image version
    #   run: |
    #     echo "SECURIA_TAG=1.1.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build and push images
      uses: docker/bake-action@v5
      with:
        source: "."
        files: "docker-compose.yaml"
        workdir: ./src
        push: true
      # env:
      #   SECURIA_TAG: ${{ env.SECURIA_TAG }}

    # - name: Build the Docker image
    #   run: |
    #     cd src
    #     docker login -u '${{ vars.REGISTRY_USER }}' -p '${{ secrets.REGISTRY_SECRET }}' ${{ vars.REGISTRY_HOST }}
    #     docker build collector_hikvision/ -t ${{ vars.REGISTRY_HOST }}/securia/collector-hikvision:latest
    #     docker push ${{ vars.REGISTRY_HOST }}/securia/collector-hikvision:latest
    #     docker build collector_simulator/ -t ${{ vars.REGISTRY_HOST }}/securia/collector-simulator:latest
    #     docker push ${{ vars.REGISTRY_HOST }}/securia/collector-simulator:latest
    #     docker build image_preprocessor/ -t ${{ vars.REGISTRY_HOST }}/securia/image-preprocessor:latest
    #     docker push ${{ vars.REGISTRY_HOST }}/securia/image-preprocessor:latest
    #     docker build securia_api/ -t ${{ vars.REGISTRY_HOST }}/securia/securia-api:latest
    #     docker push ${{ vars.REGISTRY_HOST }}/securia/securia-api:latest
    #     docker build securia_ui/ -t ${{ vars.REGISTRY_HOST }}/securia/securia-ui:latest
    #     docker push ${{ vars.REGISTRY_HOST }}/securia/securia-ui:latest
    #     docker build yolo_processor/ -t ${{ vars.REGISTRY_HOST }}/securia/yolo-processor:latest
    #     docker push ${{ vars.REGISTRY_HOST }}/securia/yolo-processor:latest
