name: Securia Push Charts

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    environment:
      name: dev

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4.2.0
      id: install
    - name: Build the Docker image
      run: |
        export $(grep -v '^#' src/.env | xargs -d '\n')
        export
        cd helm
        helm registry login -u '${{ vars.REGISTRY_USER }}' -p '${{ secrets.REGISTRY_SECRET }}' ${REGISTRY_HOST}
        for dir in charts/*/; do
          if [ -d "$dir" ]; then
            chart_name=$(basename "$dir")
            echo "Packaging chart: $chart_name"
            package_name=$(echo "${chart_name}" | tr '_' '-')
            helm package "$dir" --version ${SECURIA_VERSION}
            helm push $package_name-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia
          fi
        done

        # helm package charts/collector_hikvision --version ${SECURIA_VERSION}
        # helm package charts/image_preprocessor --version ${SECURIA_VERSION}
        # helm package charts/securia_api --version ${SECURIA_VERSION}
        # helm package charts/securia_ui --version ${SECURIA_VERSION}
        # helm package charts/yolo_processor --version ${SECURIA_VERSION}

        # helm push collector-hikvision-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia
        # helm push image-preprocessor-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia
        # helm push securia-api-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia
        # helm push securia-ui-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia
        # helm push yolo-processor-${SECURIA_VERSION}.tgz oci://${REGISTRY_HOST}/securia

        rm *tgz