name: Deploy Securia

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    environment:
      name: dev

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Apply registry secret
      uses: azure/setup-kubectl@v1
    - run: |
        export $(grep -v '^#' src/.env | xargs -d '\n')
        export
        if ! kubectl -n ${SECURIA_NAMESPACE} get secret registrypullsecret &> /dev/null; then
          echo "Secret does not exist. Creating it..."
          kubectl -n ${SECURIA_NAMESPACE} create secret docker-registry registrypullsecret \
            --docker-username=${{ vars.REGISTRY_USER }} \
            --docker-password=${{ secrets.REGISTRY_SECRET }} \
            --docker-email="securia@marnus.com" \
            --docker-server=${REGISTRY_HOST}
          echo "Secret created successfully."
        else
          echo "Secret already exists. Skipping creation."
        fi
    - name: Setup AGE
      uses: alessiodionisi/setup-age-action@v1.3.0
    - run: age --version
    - name: Setup SOPS
      uses: nhedger/setup-sops@v2
    - run: sops --version
    - uses: azure/setup-helm@v4.2.0
      id: install
    - name: Define AGE decryption secret
      run: |
        export SOPS_AGE_KEY='${{ secrets.SOPS_AGE_KEY }}'
        export $(grep -v '^#' src/.env | xargs -d '\n')
    - name: Set Chart Version
      run: |
        # echo "CHART_VERSION=1.1.${{ github.run_number }}" >> $GITHUB_ENV
        echo "CHART_VERSION=1.1.0" >> $GITHUB_ENV
    - uses: helmfile/helmfile-action@v1.9.1
      with:
        helmfile-args: apply
        helmfile-workdirectory: helm
        helm-plugins: >
          https://github.com/databus23/helm-diff,
          https://github.com/jkroepke/helm-secrets
        helmfile-auto-init: "true"
      env:
        CHART_VERSION: ${{ env.CHART_VERSION }}