name: Securia Build Images

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  #   # paths-ignore:
  #   #   - 'docs/**'
  #   # paths:
  #   #   - '**.js'
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build-push-images:
    timeout-minutes: 1440

    environment:
      name: dev

    runs-on: homelab

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup AGE
      uses: alessiodionisi/setup-age-action@v1.3.0

    - name: Check AGE version
      run: age --version

    - name: Setup SOPS
      uses: nhedger/setup-sops@v2

    - name: Check SOPS version
      run: sops --version

    - name: populate dotenvs
      run: |
        sops -i -d --input-type dotenv --output-type dotenv src/.env.secrets
        export $(grep -v '^#' src/.env.secrets | xargs -d '\n')

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < src/.env

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < heln/.env

        while IFS='=' read -r key value; do
          if [[ ! $key =~ ^# && -n $key ]]; then
            echo "$key=$value" >> $GITHUB_ENV
            echo "Set $key"
          fi
        done < src/.env.secrets
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_HOST }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ env.REGISTRY_PASSWORD }}

    - name: Build and push images
      uses: docker/bake-action@v5
      with:
        source: "."
        files: "docker-compose.yaml"
        workdir: ./src
        push: true
      env:
        CHART_VERSION: ${{ env.CHART_VERSION }}