kind: Deployment
apiVersion: apps/v1
metadata:
  name: s3emu-{{ .Values.postfix }}
  labels:
    app: s3emu-{{ .Values.postfix }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: s3emu-{{ .Values.postfix }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: s3emu-{{ .Values.postfix }}
    spec:
      containers:
        - name: s3emu-{{ .Values.postfix }}
          image: "{{ printf "%s%s/%s%s" .Values.image.registry .Values.image.path .Values.image.name .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.service.name }}
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /home/sirius/data
          {{- end }}
            - name: config
              mountPath: /home/sirius/app
              subPath: application.conf
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      enableServiceLinks: false
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.s3emu.general.app_name }}-storage
      {{- end }}
        - name: config
          configMap:
            name: s3emu-config-{{ .Values.postfix }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600