{{- if .Values.ingress.traefik_ipwhitelist -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: s3emu-ipwhitelist
  labels:
    app: securia-{{ .Values.postfix }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - 10.0.0.0/24
{{- end }}